### ISSUE TITLE
[Bug]: sample_name cannot be a number, it must be a string

### ISSUE THREAD

**Issue by mattloose** [epi2me-labs/wf-human-variation#14] opened 2022-12-16 21:10 UTC
### What happened?

Samples can be tracked by a numeric identifier. There is no way to achieve this in the workflow without adding a non numeric character - eg 12345 will not work whereas _12345 will. 

For sample_name users may have no control over the identifier that has been assigned.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

1.0.1

### Relevant log output

```shell
NA
```

**Comment by cjw85** [comment] 2022-12-16 21:17
This is caused by: https://github.com/nextflow-io/nextflow/issues/2083

We do not currently have a better workaround.

**Comment by mattloose** [comment] 2022-12-16 21:21
Would be great if nextflow can sort that out then. It's a pain that even if you quote an identifier it seems to be interpreted as an integer  - e.g "12345".

**Comment by SamStudio8** [comment] 2023-02-08 10:56
Closing as we currently have no workaround for this. We are eagerly awaiting for upstream to implement an alternative input parser.

**Closed** 2023-02-08 10:56 UTC
Labels: enhancement

**Comment by mattloose** [comment] 2023-07-16 20:21
Having just spent a lovely 30 minutes trying to work out why a script was failing, bumping this again in the vague hope that upstream might implement an input parser that handles identifiers which differ from their dogmatic view of what an identifier should be.

Or alternatively hoping that upstream are working to convince the world to stick with their dogmatic view of what identifiers should be and providing a lookup table for the billions of historical samples that do not match their dogmatic views...
